server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    #是否获取eureka服务器注册表上的注册信息
    fetchRegistry: true
    #配置这个eureka server注册中心所属的region，默认值us-east-1
    region: region1
    ##region1内的所有zone,提取第一个作为自己的zone
    availability-zones:
      region1: region1-zone1,region1-zone2
    serviceUrl:
      #region1内的所有其它zone的注册中心
      region1-zone1: http://${spring.security.user.name}:${spring.security.user.password}@region1-zone1:8761/eureka/
      region1-zone2: http://${spring.security.user.name}:${spring.security.user.password}@region1-zone2:8762/eureka/
  server: 
    #关闭eureka的自我保护模式
    enable-self-preservation: false
  instance:
    #主机名称
    hostname: region1-zone1
    
    
spring:
  security:
    user:
      name: admin
      password: 123456
  

